### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [TelequestInternetSolutionsGmbH/questFON-Call-Tracking#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on "_tid" when generating the url
'https://cdn.questfon.cloud/js/qfct.js?id='+ _tid
2) We are seeing "Error thrown by third party script. Check your browser's developer console for more details." while running the script.
![Screenshot 2020-12-04 at 2 02 46 PM](https://user-images.githubusercontent.com/53495700/101219923-9bcef700-3639-11eb-9ebd-40a07bfed03e.png)
3) We are seeing "/ip-reputation returned error: [500]" for the url "https://cdn.questfon.cloud/js/qfct.js". Please resolve the issue.

**Comment by czorc** [comment]
Thank you very much for your feedback.
The parameter is now passed in url-encoded form.
The external script has been changed so that it does not throw any errors if GA is not available.

We could not reproduce the third point. Under certain circumstances, the test was during an update on our part.
If the error persists, please let us know how we can test how we can reproduce the test case.

Many thanks
